# # docker build -t comfy/base:cuda12.8 -f docker_cuda/Dockerfile.base ./
# # docker build -t comfy/base:cuda13 -f docker_cuda/Dockerfile.base ./

# FROM nvidia/custom_base:cuda12.8
FROM nvidia/custom_base:cuda13

#guarda capa
COPY requirements.txt .
RUN pip install -r requirements.txt

COPY manager_requirements.txt .
RUN pip install -r manager_requirements.txt


# Dependencias mínimas de ComfyUI
RUN pip install \
    numpy \
    pillow \
    tqdm \
    pyyaml \
    psutil \
    einops \
    safetensors \
    opencv-python-headless

RUN pip install \
  torchsde==0.2.6 \
  scipy 

RUN pip install \
    omegaconf \
    torchdiffeq \
    torchsde \
    open-clip-torch \
    matrix-nio 
    
RUN pip install --no-cache-dir --upgrade \
    huggingface_hub==0.36.2 \
    diffusers==0.30.3 \
    transformers==4.57.3 \
    accelerate==1.12.0
    
# RUN pip install flash-attn --no-build-isolation || true




# RUN git clone --branch v2.2.0 https://github.com/thu-ml/SageAttention.git /tmp/sageattention && \
# cd /tmp/sageattention && \
# python3 /tmp/patch_setup.py && \
# pip install --no-build-isolation .

# RUN apt update && apt install -y sudo
