# CUDA 12.8 Base Image for ComfyUI
# docker build -t nvidia/custom_base:cuda12.8 -f docker_cuda/Dockerfile.cuda12.8 .

FROM nvidia/cuda:12.8.0-cudnn-devel-ubuntu22.04

ARG CUDA_ARCHITECTURES="8.0;8.6"

ENV PYTHONUNBUFFERED=1
ENV PIP_NO_CACHE_DIR=1

# Install basic system dependencies
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    git \
    ffmpeg \
    libgl1 \
    sox  \
    ninja-build \
    libglib2.0-0 \
    build-essential \
    curl \
    wget \
    && apt clean

# Alias python
# RUN ln -s /usr/bin/python3 /usr/bin/python

# Update pip
RUN pip install setuptools wheel
RUN pip install --upgrade pip setuptools wheel pytorch-lightning

# PyTorch CUDA 12.8
RUN pip install \
 torch==2.7.1+cu128 \
 torchvision==0.22.1+cu128 \
 torchaudio==2.7.1+cu128 \
 --index-url https://download.pytorch.org/whl/cu128

RUN pip install sageattention

# Set working directory
WORKDIR /app